"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireUserForAction } from "@/lib/auth";
import { canManageProjectTypes } from "@/lib/permissions";
export type ProjectTypeFormState = { success?: boolean; error?: string };
const schema = z.object({ id: z.string().optional(), clientId: z.string().min(1), name: z.string().min(2, 'Project type name is required.'), code: z.string().trim().min(1, 'Project type code is required.').max(30), isActive: z.union([z.literal('on'), z.literal('true'), z.literal('1')]).optional() });
async function requireAccess() { const user = await requireUserForAction(); if (!canManageProjectTypes(user)) throw new Error('You are not allowed to manage project types.'); return user; }
export async function createProjectTypeAction(_prev: ProjectTypeFormState, formData: FormData): Promise<ProjectTypeFormState> { try { await requireAccess(); const parsed = schema.safeParse({ clientId: String(formData.get('clientId') ?? ''), name: String(formData.get('name') ?? ''), code: String(formData.get('code') ?? ''), isActive: formData.get('isActive') ?? 'on' }); if (!parsed.success) return { success: false, error: parsed.error.issues[0]?.message || 'Invalid project type payload.' }; await db.projectType.create({ data: { clientId: parsed.data.clientId, name: parsed.data.name.trim(), code: parsed.data.code.trim().toUpperCase(), isActive: Boolean(parsed.data.isActive) } }); revalidatePath(`/clients/${parsed.data.clientId}/project-types`); revalidatePath('/projects/new'); return { success: true }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : 'Something went wrong.' }; } }
export async function updateProjectTypeAction(_prev: ProjectTypeFormState, formData: FormData): Promise<ProjectTypeFormState> { try { await requireAccess(); const parsed = schema.safeParse({ id: String(formData.get('id') ?? ''), clientId: String(formData.get('clientId') ?? ''), name: String(formData.get('name') ?? ''), code: String(formData.get('code') ?? ''), isActive: formData.get('isActive') ?? undefined }); if (!parsed.success || !parsed.data.id) return { success: false, error: parsed.success ? 'Project type is required.' : parsed.error.issues[0]?.message }; await db.projectType.update({ where: { id: parsed.data.id }, data: { name: parsed.data.name.trim(), code: parsed.data.code.trim().toUpperCase(), isActive: Boolean(parsed.data.isActive) } }); revalidatePath(`/clients/${parsed.data.clientId}/project-types`); revalidatePath(`/clients/${parsed.data.clientId}/project-types/${parsed.data.id}`); revalidatePath('/projects'); return { success: true }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : 'Something went wrong.' }; } }
export async function toggleProjectTypeStatusAction(formData: FormData) { await requireAccess(); const projectTypeId = String(formData.get('projectTypeId') || ''); if (!projectTypeId) throw new Error('Project type is required.'); const row = await db.projectType.findUnique({ where: { id: projectTypeId } }); if (!row) throw new Error('Project type not found.'); await db.projectType.update({ where: { id: projectTypeId }, data: { isActive: !row.isActive } }); revalidatePath(`/clients/${row.clientId}/project-types`); }
