"use client";
import { useActionState } from "react";
import { FormLabel } from "@/components/ui/form-label";
import type { LanguageFormState } from "@/lib/actions/language-actions";
const initialState: LanguageFormState = {};
export function LanguageForm({ mode, action, initialValues }: { mode: "create" | "edit"; action: (state: LanguageFormState, formData: FormData) => Promise<LanguageFormState>; initialValues?: { id?: string; name?: string; code?: string; isActive?: boolean; }; }) {
 const [state, formAction, pending] = useActionState(action, initialState);
 return <form action={formAction} className="card p-6">{mode==="edit"&&initialValues?.id?<input type="hidden" name="id" value={initialValues.id}/>:null}<h2 className="section-title">{mode==="create"?"Create language":"Edit language"}</h2><p className="section-subtitle">Fields marked <span className="text-red-600">*</span> are required.</p>{state?.error?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{state.error}</div>:null}{state?.success?<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Language saved successfully.</div>:null}<div className="mt-5 space-y-4"><div><FormLabel htmlFor="name" required>Language name</FormLabel><input id="name" name="name" className="input" defaultValue={initialValues?.name ?? ""} required/></div><div><FormLabel htmlFor="code" required>Language code</FormLabel><input id="code" name="code" className="input" defaultValue={initialValues?.code ?? ""} required/></div><label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700"><input type="checkbox" name="isActive" defaultChecked={initialValues?.isActive ?? true}/>Active language</label><button className="btn-primary w-full" disabled={pending}>{pending?"Saving...":mode==="create"?"Create language":"Save changes"}</button></div></form>
}
